Add files via upload
update /nodepool/elements

diff --git a/nodepool/elements/stackviz/install.d/89-prepare-stackviz b/nodepool/elements/stackviz/install.d/89-prepare-stackviz
--- a/nodepool/elements/stackviz/install.d/89-prepare-stackviz
+++ b/nodepool/elements/stackviz/install.d/89-prepare-stackviz
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (C) 2011-2013 OpenStack Foundation
+# Copyright (C) 2014 Hewlett-Packard Development Company, L.P.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -15,16 +15,25 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# dib-lint: disable=setu setpipefail
+# dib-lint: disable=setu setpipefail sete
 if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
     set -x
 fi
-set -e
 
-# Unset the download cache for this invocation to prevent bleed from build host
-unset PIP_DOWNLOAD_CACHE
+STACKVIZ_NPM_TIMEOUT="15m"
+STACKVIZ_DIR=/opt/stackviz
+cp -r /opt/git/openstack/stackviz $STACKVIZ_DIR
 
-/bin/bash /opt/build_git/openstack-infra/system-config/install_puppet.sh
-/bin/bash /opt/build_git/openstack-infra/system-config/install_modules.sh
+cd $STACKVIZ_DIR
 
-install -m 0755 -o root -g root $(dirname $0)/../bin/prepare-node /usr/local/bin
+timeout $STACKVIZ_NPM_TIMEOUT npm install
+ret=$?
+
+if [[ $ret -eq 0 ]]; then
+    npm run prod && rm -rf node_modules/
+else
+    echo "stackviz build aborted due to npm error"
+    rm -rf $STACKVIZ_DIR
+fi
+
+exit 0
